### ISSUE TITLE
Missing from README: What is this? Why should I care?

### ISSUE THREAD

**Issue by bmulholland** [testdouble/mocktail#24]
I am intrigued in concept by the idea of mocktail, but I can't easily understand what it is. Ideally, I'd see a concise description of the problem, and how mocktail solves that. Perhaps a quick code example, showing before/after mocktail could help?

There's nothing about this in the README, and while there seems to be solid docs (nice work!) on implementing mocktail etc, they seem to make me get into the details before I can understand whether it's worth that effort.

**Comment by searls** [comment]
Thanks for the feedback.
