### ISSUE TITLE
RSpec must require Mocktail before adding DSL?

### ISSUE THREAD

**Issue by kevin-j-m** [testdouble/mocktail#4]
After adding Mocktail and following the [README instructions](https://github.com/testdouble/mocktail#sprinkle-in-the-dsl) to [configure RSpec](https://github.com/kevin-j-m/ruby_cover_band/commit/fd65d568b556c81528c99642406b59e1dd9cf557), I receive the following error when attempting to run any tests, unless I `require "mocktail"` in the `spec_helper.rb`:

```
An error occurred while loading spec_helper.
Failure/Error: config.include Mocktail::DSL

NameError:
  uninitialized constant Mocktail
```

I confirmed I'm also seeing the same behavior when adding Mocktail to an existing (and private) Rails application.

If that seems reasonable and expected, I can push PR that updates the README to say that it should be included, but in case I'm doing something silly, I figured I'd bring this up as an issue first. 

I can also try to replicate on a fresh rails app and/or gem, if you'd like different/more easily reproducible replication steps.

**Comment by searls** [comment]
Sorry for not getting back to you about this forever—do you have `require: false` in your Gemfile?

**Comment by kevin-j-m** [comment]
When I originally reported this, it was from adding to a [gem as a development dependency](https://github.com/kevin-j-m/ruby_cover_band/commit/1502a68fe423fa035ad92491640d6f40ee6d8956). I found if I [require the library](https://github.com/kevin-j-m/ruby_cover_band/commit/fd65d568b556c81528c99642406b59e1dd9cf557#diff-89eebfcbc0f14b6d989517837ca1e94fce4e2ce9a03233641cd936f2b8d2ed94R4), then I would avoid the `NameError`.

Revisiting this now, I moved it out of the gemspec and [into the Gemfile](https://github.com/kevin-j-m/ruby_cover_band/commit/af7c4e3a032883b35b49022b7a066c23ccbdd585), to be consistent with the [README](https://github.com/testdouble/mocktail#install-the-gem). I moved it out of the [test group](https://github.com/kevin-j-m/ruby_cover_band/commit/685f6ed9cbaaa05b8da8dd44a0b3106f7e5f2316). I also __added__ [require: false](https://github.com/kevin-j-m/ruby_cover_band/commit/e7a418f1a0e6404ed14c015ffb15b94a862a0b5d).

In all of those scenarios, I'd see the `NameError` unless I require the library in the `spec_helper`.

Now, for caveats, this isn't a "real" gem. It's a repo I have that has some example code for a conference talk, so it may not be the best use case. It was the thing I had most easily on hand that I could link public commits to about progress on, and that's why I picked it a while ago to give this library a try.

If no one else is reporting this and aren't having issues with the README instructions using rspec, I have no issue with closing this.

**Comment by searls** [comment]
While I don't know what you might be running into, I want to make sure there's not something wrong here—mocktail has almost no usage yet because we haven't been explaining or promoting it much. 

AFAICT, the library "requires itself" (a misnomer) in the sense that everything that needs to be loaded is in the conventionally-expected place ([lib/mocktail.rb](lib/mocktail.rb)), so I'm a little fuzzy on what might be wrong here.

I mean, I presume if you haven't done something to `require "mocktail"`, then of course `Mocktail::DSL` isn't defined. Is there something else going on here?

**Comment by kevin-j-m** [comment]
Is the expectation that users should need to `require "mocktail"` before using it?

If so, do you think adding that info to the [Ready to order?](https://github.com/testdouble/mocktail#ready-to-order) section of the README would be helpful? That's part of what I was asking in my (likely poorly worded) initial issue comment.

If not, I may have an issue or something funny going on with my usage.

Thanks for the follow-up! I'm looking forward to seeing this more and more in the community as a former Mockito user/fan. Great stuff here.

**Comment by searls** [comment]
Thanks Kevin. Going to close this as I don't think this indicates an issue beyond needing to make sure the library is required
