### ISSUE TITLE
Ruby 2.7.4 Test Failure

### ISSUE THREAD

**Issue by kevin-j-m** [testdouble/mocktail#5]
The [gemspec](https://github.com/testdouble/mocktail/blob/3d3ca74695d86f4e5049ea3dea0252e37359e410/mocktail.gemspec#L11) mentions 2.7 as the minimum ruby version; however, running the test suite does not appear to pass (at least for me, locally) when using 2.7.4.

## Reproduction Steps

1. Set ruby version to 2.7.4
2. Run tests (I did so with `rake`)

## Expected

Tests Pass

## Actual

```
  1) Error:
VerifyTest#test_uses_a_captor_for_a_complex_arg:
ArgumentError: ArgumentError
    /mocktail/lib/mocktail/handles_dry_call/validates_arguments.rb:41:in `validate'
    /mocktail/lib/mocktail/handles_dry_call.rb:14:in `handle'
    /mocktail/lib/mocktail/imitates_type/makes_double/declares_dry_class.rb:42:in `block (2 levels) in define_double_methods!'
    /mocktail/test/safe/verify_test.rb:135:in `test_uses_a_captor_for_a_complex_arg'

61 runs, 295 assertions, 0 failures, 1 errors, 0 skips
```

## Notes

I also ran the tests locally with ruby 3.0.1, and tests passed for me then.

**Comment by al2o3cr** [comment]
0.0.2 bumped the minimum version to 3.0: https://github.com/testdouble/mocktail/blob/3b6a0e0c6e061b532ff35b81a528d8d56fbec261/mocktail.gemspec#L11
